spring.application.name=pidro

# Basic Postgres connection (adjust for your environment)
spring.datasource.url=jdbc:postgresql://localhost:5432/pidro
spring.datasource.username=postgres
spring.datasource.password=2733

# JPA/Hibernate settings for quick demos
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
